# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

    before_all do
        # ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    end

##  desc "Runs all the tests"
##  lane :test do
##    gradle(task: "test")
##  end
    lane :qa do
        notes = get_changelog_from_tag match_tag: "qa*"
        opt_version_number = get_version_from_tag(match_tag: "qa*")
        opt_build_number = get_commit_count.to_i

        require 'tempfile'

        changelog = Tempfile.new('changelog')
        changelog.write(notes)
        changelog.close

        notes_path = changelog.path
        opt_groups= "qa-team"

        crashlytics_api_token = ENV["CRASHLYTICS_API_TOKEN"]
        crashlytics_api_secret = ENV["CRASHLYTICS_BUILD_SECRET"]
        config_url = ENV["APP_CONFIG_URL"]

        gradle(task: "clean assembleDebug crashlyticsUploadDistributionDebug", flags: "-PversionNumber=#{opt_version_number} -PbuildNumber=#{opt_build_number} -PbetaDistributionReleaseNotesFilePath=#{notes_path} -PbetaDistributionGroupAliases=#{opt_groups} -PbetaDistributionNotifications=true -PcrashlyticsApiKey=#{crashlytics_api_token} -PcrashlyticsApiSecret=#{crashlytics_api_secret}")
    end

    lane :rel do
        notes = get_changelog_from_tag match_tag: "rel*"
        opt_version_number = get_version_from_tag(match_tag: "rel*")
        opt_build_number = get_commit_count.to_i

        require 'tempfile'

        changelog = Tempfile.new('changelog')
        changelog.write(notes)
        changelog.close

        notes_path = changelog.path
        opt_groups= "rel-team"

        crashlytics_api_token = ENV["CRASHLYTICS_API_TOKEN"]
        crashlytics_api_secret = ENV["CRASHLYTICS_BUILD_SECRET"]
        config_url = ENV["APP_CONFIG_URL"]

        gradle(task: "clean assembleRelease crashlyticsUploadDistributionRelease" ,flags: "-PversionNumber=#{opt_version_number} -PbuildNumber=#{opt_build_number} -PbetaDistributionReleaseNotesFilePath=#{notes_path} -PbetaDistributionGroupAliases=#{opt_groups} -PbetaDistributionNotifications=true -PcrashlyticsApiKey=#{crashlytics_api_token} -PcrashlyticsApiSecret=#{crashlytics_api_secret}",properties: {
                 "android.injected.signing.store.file" => "keystore",
                 "android.injected.signing.store.password" => "android",
                 "android.injected.signing.key.alias" => "android",
                 "android.injected.signing.key.password" => "android",
             }
        )
        end
    end

##  desc "Submit a new Beta Build to Crashlytics Beta"
##  lane :beta do
##    gradle(task: "clean assembleRelease")
##    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
##  end

##  desc "Deploy a new version to the Google Play"
##  lane :deploy do
##    gradle(task: "clean assembleRelease")
##    upload_to_play_store
##  end
end
